version: '3.9'
services:
  sqlite3:
    container_name: sqlite3_container
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - sqlite_data
    ports:
      - '9000:9000' # expose ports - HOST:CONTAINER
    restart: unless-stopped
  
  banco:
    container_name: python
    build: .
    volumes:
    - .:/app
    depends_on:
      - sqlite3
    links:
      - sqlite3



volumes:
  sqlite_data: